language: node_js
node_js:
  - "10"
stages:
  # Running tests on all branches
  - name: test/build
    if: (NOT type IN (pull_request)) AND (NOT branch = master)

  # Deployment
  - name: test/build/deploy
    if: (NOT type IN (pull_request)) AND (branch = master)
jobs:
  include:
    # Run tests with coverage
    - stage: test
      script:
        - npm run test -- --coverage
        - npm run build

    # Build and deploy to production
    - stage: deploy
      script:
        - npm run test -- --coverage
        - npm run build
        - SFTP_USER=${SFTP_USER} SFTP_PASS=${SFTP_PASS} SFTP_HOST=${SFTP_HOST} npm run deploy
notifications:
  email:
    on_success: never
    on_failure: change
